// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatSubscriptionController from "./chat_subscription_controller"
application.register("chat-subscription", ChatSubscriptionController)

import CreateCompanionController from "./create_companion_controller"
application.register("create-companion", CreateCompanionController)

import CreateTripController from "./create_trip_controller"
application.register("create-trip", CreateTripController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SelectFromCardsController from "./select_from_cards_controller"
application.register("select-from-cards", SelectFromCardsController)
